# Generated by Django 5.2.5 on 2025-08-18 16:45

import Resources.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('subject', models.CharField(max_length=128)),
                ('semester', models.CharField(max_length=64)),
                ('course_code', models.CharField(blank=True, max_length=64, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ResourceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=Resources.models.user_upload_path)),
                ('file_url', models.TextField(blank=True, null=True)),
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=128, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Resources.resource')),
            ],
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=512)),
                ('mime_type', models.CharField(blank=True, max_length=128, null=True)),
                ('size', models.BigIntegerField()),
                ('total_chunks', models.PositiveIntegerField()),
                ('uploaded_chunks', models.PositiveIntegerField(default=0)),
                ('temp_dir', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('aborted', 'Aborted')], default='initiated', max_length=16)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['owner'], name='Resources_r_owner_i_06a512_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['subject'], name='Resources_r_subject_08f585_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['course_code'], name='Resources_r_course__a1466c_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcefile',
            index=models.Index(fields=['owner'], name='Resources_r_owner_i_7a16dd_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcefile',
            index=models.Index(fields=['file_id'], name='Resources_r_file_id_7294d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcefile',
            unique_together={('owner', 'file_id')},
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['owner'], name='Resources_u_owner_i_5699c0_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['status'], name='Resources_u_status_cb105f_idx'),
        ),
    ]
