# Generated by Django 5.2.5 on 2025-08-20 05:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='downloads_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='rating_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='resource',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resourcefile',
            name='downloads_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ResourceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['resource'], name='Resources_r_resourc_4d6eb3_idx'), models.Index(fields=['user'], name='Resources_r_user_id_ae7fa5_idx')],
                'unique_together': {('resource', 'user')},
            },
        ),
    ]
