# Generated by Django 5.2.5 on 2025-08-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0002_resource_downloads_count_resource_rating_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resourcefile',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
